In [42]:
import pandas as pd

In [56]:
file = '../data/training_data.csv'

df = pd.read_csv(file, skiprows=13) # 13 rows are skipped because the NASA POWER API's first 
                                    # 13 rows are metadata about the dataset therefore skipped
display(df.head()) # Initial DataFrame

df = df.rename(columns={'ALLSKY_SFC_SW_DWN' : 'GHI(W/m2)' , 'WSC' : 'Windspeed(m/s)'}) # Renamed to simpler names with their units

# Renaming to datetime object instead of using 3 diff rows
time_column = df[['YEAR' , 'MO' , 'DY' , 'HR']].rename(columns={'YEAR' : 'year' , 'MO' : 'month' , 'DY' : 'day' , 'HR' : 'hour'}) 
df['Time'] = pd.to_datetime(time_column)
df = df.set_index('Time')
df = df.drop(columns=['YEAR' , 'MO' , 'DY' , 'HR'])

display(df.head())

   YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN    WSC
0  2014   1   1   0                0.0  11.37
1  2014   1   1   1                0.0  11.22
2  2014   1   1   2                0.0  11.12
3  2014   1   1   3                0.0  10.67
4  2014   1   1   4                0.0  10.39

                     GHI(W/m2)  Windspeed(m/s)
Time
2014-01-01 00:00:00        0.0           11.37
2014-01-01 01:00:00        0.0           11.22
2014-01-01 02:00:00        0.0           11.12
2014-01-01 03:00:00        0.0           10.67
2014-01-01 04:00:00        0.0           10.39